question_data = {"response_code": 0,
                 "results": [
                     {
                         "category": "Science: Computers",
                         "type": "boolean",
                         "difficulty": "easy",
                         "question": "The logo for Snapchat is a Bell.",
                         "correct_answer": "False",
                         "incorrect_answers": ["True"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                      "question": "&quot;Windows NT&quot; is a monolithic kernel.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                      "question": "The open source program Redis is a relational database server.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                      "question": "AMD created the first consumer 64-bit processor.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
                      "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "question": "Time on Computers is measured via the EPOX System.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                      "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
                      "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
                      "correct_answer": "True", "incorrect_answers": ["False"]}]}
